### ISSUE TITLE
React manifest.json still has "sample app" short name and name

### ISSUE THREAD

**Issue by montsamu** [StakeTree/site#21]
This is pretty useless, but it's technically valid -- the best/worst kind of valid! -- and more of a "sample test issue" for me to match with a sample pull request, to see how it would be to work in this GitHub project, and begin to contribute.

**Comment by nieldlr** [comment]
Merged! 👍

**Comment by montsamu** [comment]
I think I "did it wrong"; I'd meant to have a purpose-named branch, and to associate the pull request with the issue, and I don't think I managed either!

**Comment by nieldlr** [comment]
Heya @montsamu. No worries at all. When things get a bit more busier in here we can think of getting some process in place. But for now, I totally understood what needed to happen :) 
A contribution guide can come later.

Thanks again!

(Btw, this is live now: https://staketree.com/manifest.json 👌)
