### ISSUE TITLE
The alt text for all creator images is static

### ISSUE THREAD

**Issue by montsamu** [StakeTree/site#23]
See:

https://staketree.com/rhyslindmark

The alt text for Rhys' picture is still "Niel's face" as this is hardcoded in CreatorPage.js instead of being read as a property of the specific creator object (e.g. this.state.creator.name which does not yet exist, or this.state.creator.title perhaps being a better temporary fill-in).

**Comment by nieldlr** [comment]
Great one @montsamu. I'm still adjusting/thinking on how to store some of the variables for the creator page & not sure if we will have the alt-text customizable or not yet. However, I'd love to keep making StakeTree as accessible as possible. I think for now though, to make things simpler, we can make the alt text generic. Something like "Profile Picture".

How comfortable are you with React? If you want to & have the time to contribute, feel free to jump on this one. No rush at all here though. Just lemme know.

I'm going to write a quick README soon to explain how this site works. How to bundle etc. Stay tuned for that.

**Comment by montsamu** [comment]
Very comfortable, and I'll push a placeholder like "Profile Picture for [this.state.creator.name]" soon. Excellent job with the README -- have you spent much thought on the data layer after "creators.json" is retired? I guess some of that depends on how/where you're hosting the site, which I didn't poke on further past Cloudflare.
