### ISSUE TITLE
Addresses are not checksummed

### ISSUE THREAD

**Issue by veox** [StakeTree/site#4]
Present in [these files](https://github.com/StakeTree/site/search?utf8=%E2%9C%93&q=0xa899495d47b6a575c830ffc330bc83318df46a44&type=).

Simplest way to fix is probably copy-pasting from [Etherscan page for the address](https://etherscan.io/address/0xa899495d47b6a575c830ffc330bc83318df46a44).

**Comment by nieldlr** [comment]
Heya @veox,

could you perhaps explain a bit more on what you mean by checksumming the address?

**Comment by veox** [comment]
I mean having (note the capitals):

`0xa899495d47B6a575c830Ffc330BC83318Df46a44`

Instead of (all-lowercase):

`0xa899495d47b6a575c830ffc330bc83318df46a44`

It's a simple scheme to ensure (with a small error rate) that the address is correct if manually copied into external programs.

See [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) for details.

**Comment by nieldlr** [comment]
Ah! Yes! Thanks so much for catching that. You're totally right.

I'm going to update this!
